import * as functions from './modules/functions.js';
import * as sliders from './modules/sliders.js';

functions.burger();
functions.anchors();
functions.openMoreMobile();
functions.upBtn();
functions.homepageMainDataPicker();
functions.homepageMainRoomPicker();
functions.homepageMainGuestPicker();
// functions.modalRoomPicker();
functions.modalGuestPicker();
functions.modal();
functions.supportMain();
functions.mobileSupportChat();
// functions.supportDataPicker();
// functions.supportGuestPicker();
functions.supportRooms();
// functions.homepageModalWithDataRoomPicker();
functions.homepageModalWithDataGuestPicker();
// functions.homepageSupportChat();
functions.homepageBooking();
sliders.homepageAboutInfoSlider();
sliders.homepageAboutServicesSlider();
sliders.roomsItemSlider();
