import * as functions from './modules/functions.js';
import * as sliders from './modules/sliders.js';
import * as ymaps from './modules/ymaps.js';

// ymaps.ymapMain();
functions.burger();
functions.anchors();
functions.openMoreMobile();
functions.upBtn();
functions.homepageMainDataPicker();
functions.homepageMainRoomPicker();
functions.homepageMainGuestPicker();
functions.modalGuestPicker();
functions.modal();
functions.supportMain();
functions.mobileSupportChat();
functions.supportRooms();
functions.homepageModalWithDataGuestPicker();
functions.homepageBooking();
sliders.homepageAboutInfoSlider();
sliders.homepageAboutServicesSlider();
sliders.roomsItemSlider();
